name: Publish Docker image
on: [push]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secret.DOCKER_USERNAME }}
          password: ${{ secret.DOCKER_PASSWORD }}
          repository: lhy1024/bench
          tag_with_ref: true
          tag_with_sha: true
